[patch.crates-io]
font-types = {git="https://github.com/googlefonts/fontations.git"}
read-fonts = {git="https://github.com/googlefonts/fontations.git"}
write-fonts = {git="https://github.com/googlefonts/fontations.git"}

[workspace]

members = [
    "fontdrasil",
    "fontbe",
    "fontir",
    "glyphs-reader",
    "glyphs2fontir",
    "ufo2fontir",
    "fontc",    
]
